--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/new_ParticleAPI
build-by-default: true
branches:
- master
projects:
  ParticleAPI:
    path: "ParticleAPI/"
    model: virion
    type: library
...
